# Generated by Django 5.2.7 on 2025-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEMP_ALTA', 'Temperatura Alta'), ('TEMP_BAIXA', 'Temperatura Baixa'), ('IMIDADE_BAIXA', 'Umidade Baixa')], max_length=20)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
